-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 4-Dec-2016 14:51:15
-- Path: /home/nrozsa/Input_system/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Input_register IS


  SIGNAL output_int: STD_LOGIC_VECTOR(2 DOWNTO 0);

BEGIN

  output <= output_int;


  value_reg_2_inst: dfa11 PORT MAP (input(2), reset, clk, output_int(2));
  value_reg_1_inst: dfa11 PORT MAP (input(1), reset, clk, output_int(1));
  value_reg_0_inst: dfa11 PORT MAP (input(0), reset, clk, output_int(0));

END extracted;



