-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 4-Dec-2016 15:36:30
-- Path: /home/nrozsa/Input_system/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Input_fsm IS

  SIGNAL n13: STD_LOGIC;
  SIGNAL new_state_1_port: STD_LOGIC;
  SIGNAL n12: STD_LOGIC;
  SIGNAL n16: STD_LOGIC;
  SIGNAL n17: STD_LOGIC;
  SIGNAL n15: STD_LOGIC;
  SIGNAL n1: STD_LOGIC;
  SIGNAL state_1_port: STD_LOGIC;
  SIGNAL state_0_port: STD_LOGIC;
  SIGNAL n14: STD_LOGIC;
  SIGNAL n18: STD_LOGIC;

  SIGNAL enable_int: STD_LOGIC_VECTOR(1 DOWNTO 0);

BEGIN

  enable <= enable_int;


  U26: iv110 PORT MAP (state_0_port, n16);
  U24: iv110 PORT MAP (tf_rise, n17);
  U22: iv110 PORT MAP (n12, enable_int(1));
  U17: na210 PORT MAP (enable_int(0), n14, n13);
  U16: na210 PORT MAP (n12, n13, new_state_1_port);
  U20: na210 PORT MAP (n18, dec_in(2), n14);
  state_reg_0_inst: dfa11 PORT MAP (n1, reset, clk, state_0_port);
  state_reg_1_inst: dfa11 PORT MAP (new_state_1_port, reset, clk, state_1_port);
  U19: no210 PORT MAP (n16, n17, n15);
  U21: no210 PORT MAP (dec_in(1), dec_in(0), n18);
  U18: no310 PORT MAP (n14, state_1_port, n15, n1);
  U25: no310 PORT MAP (state_1_port, tf_rise, n16, enable_int(0));
  U23: na310 PORT MAP (n16, n17, state_1_port, n12);

END extracted;



