-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 4-Dec-2016 16:48:28
-- Path: /home/nrozsa/Input_system/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Input_system IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37: STD_LOGIC;
  SIGNAL enable_0_port: STD_LOGIC;
  SIGNAL t_e_enc_2_port: STD_LOGIC;
  SIGNAL t_e_enc_1_port: STD_LOGIC;
  SIGNAL enable_1_port: STD_LOGIC;
  SIGNAL t_e_enc_0_port: STD_LOGIC;
  SIGNAL tf: STD_LOGIC;
  SIGNAL t_e_logic_1_port: STD_LOGIC;
  SIGNAL t_e_logic_2_port: STD_LOGIC;
  SIGNAL t_e_logic_0_port: STD_LOGIC;

  SIGNAL t_e_int: STD_LOGIC_VECTOR(2 DOWNTO 0);

BEGIN

  t_e <= t_e_int;


  lbl4_U18: mu111 PORT MAP (N_6, N_11, enable_1_port, N_7);
  lbl4_U23: mu111 PORT MAP (N_17, N_33, enable_0_port, N_20);
  lbl4_U27: mu111 PORT MAP (N_28, N_34, enable_0_port, N_32);
  lbl1_U29: na210 PORT MAP (N_29, N_10, t_e_enc_0_port);
  lbl1_U23: na210 PORT MAP (N_8, N_25, N_1);
  lbl1_U21: na210 PORT MAP (p_r, p_l, N_5);
  lbl1_U30: na210 PORT MAP (N_8, N_9, N_10);
  lbl5_U17: na210 PORT MAP (enable_0_port, N_30, N_2);
  lbl5_U16: na210 PORT MAP (N_13, N_2, N_12);
  lbl5_U20: na210 PORT MAP (N_31, t_e_enc_2_port, N_30);
  lbl4_U25: na210 PORT MAP (t_e_int(1), enable_1_port, N_17);
  lbl4_U30: na210 PORT MAP (t_e_int(0), enable_1_port, N_28);
  lbl4_U28: na210 PORT MAP (t_e_enc_0_port, N_35, N_34);
  lbl4_U24: na210 PORT MAP (t_e_enc_1_port, N_35, N_33);
  lbl1_U22: ex210 PORT MAP (N_1, p_u, N_3);
  lbl1_U31: ex210 PORT MAP (p_u, p_d, N_9);
  lbl1_U25: ex210 PORT MAP (p_r, N_25, N_22);
  lbl1_U18: na310 PORT MAP (N_3, N_5, N_15, t_e_enc_2_port);
  lbl5_U23: na310 PORT MAP (N_16, N_18, N_26, N_13);
  lbl1_U24: no310 PORT MAP (N_24, p_f, N_22, t_e_enc_1_port);
  lbl5_U18: no310 PORT MAP (N_30, N_26, N_19, N_21);
  lbl5_U25: no310 PORT MAP (N_26, tf, N_16, enable_0_port);
  lbl2_U6: iv110 PORT MAP (frame, N_36);
  lbl1_U26: iv110 PORT MAP (p_d, N_25);
  lbl1_U33: iv110 PORT MAP (p_f, N_29);
  lbl1_U27: iv110 PORT MAP (N_23, N_24);
  lbl5_U26: iv110 PORT MAP (N_27, N_16);
  lbl5_U24: iv110 PORT MAP (tf, N_18);
  lbl5_U22: iv110 PORT MAP (N_13, enable_1_port);
  lbl4_U21: iv110 PORT MAP (enable_0_port, N_4);
  lbl4_U17: iv110 PORT MAP (N_7, t_e_logic_2_port);
  lbl4_U22: iv110 PORT MAP (N_20, t_e_logic_1_port);
  lbl4_U26: iv110 PORT MAP (N_32, t_e_logic_0_port);
  lbl4_U29: iv110 PORT MAP (enable_1_port, N_35);
  lbl2_U5: no210 PORT MAP (N_37, N_36, tf);
  lbl1_U28: no210 PORT MAP (p_l, p_u, N_23);
  lbl1_U20: no210 PORT MAP (N_8, N_25, N_14);
  lbl1_U32: no210 PORT MAP (p_r, p_l, N_8);
  lbl1_U19: no210 PORT MAP (p_f, N_14, N_15);
  lbl5_U19: no210 PORT MAP (N_16, N_18, N_19);
  lbl5_U21: no210 PORT MAP (t_e_enc_1_port, t_e_enc_0_port, N_31);
  lbl4_U20: no210 PORT MAP (t_e_enc_2_port, N_4, N_6);
  lbl4_U19: no210 PORT MAP (enable_0_port, t_e_int(2), N_11);
  lbl2_tf_reg: dfa11 PORT MAP (frame, reset, clk, N_37);
  lbl3_value_reg_2_inst: dfa11 PORT MAP (t_e_logic_2_port, reset, clk, t_e_int(2));
  lbl3_value_reg_1_inst: dfa11 PORT MAP (t_e_logic_1_port, reset, clk, t_e_int(1));
  lbl3_value_reg_0_inst: dfa11 PORT MAP (t_e_logic_0_port, reset, clk, t_e_int(0));
  lbl5_state_reg_0_inst: dfa11 PORT MAP (N_21, reset, clk, N_27);
  lbl5_state_reg_1_inst: dfa11 PORT MAP (N_12, reset, clk, N_26);

END extracted;



