-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 4-Dec-2016 13:54:01
-- Path: /home/nrozsa/Input_system/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Register_logic IS

  SIGNAL n16: STD_LOGIC;
  SIGNAL n14: STD_LOGIC;
  SIGNAL n13: STD_LOGIC;
  SIGNAL n15: STD_LOGIC;
  SIGNAL n18: STD_LOGIC;
  SIGNAL n17: STD_LOGIC;
  SIGNAL n22: STD_LOGIC;
  SIGNAL n21: STD_LOGIC;
  SIGNAL n19: STD_LOGIC;
  SIGNAL n23: STD_LOGIC;
  SIGNAL n20: STD_LOGIC;

  SIGNAL output_int: STD_LOGIC_VECTOR(2 DOWNTO 0);

BEGIN

  output <= output_int;


  U21: iv110 PORT MAP (enable(0), n16);
  U17: iv110 PORT MAP (n13, output_int(2));
  U22: iv110 PORT MAP (n17, output_int(1));
  U26: iv110 PORT MAP (n21, output_int(0));
  U29: iv110 PORT MAP (enable(1), n20);
  U20: no210 PORT MAP (enc_in(2), n16, n14);
  U19: no210 PORT MAP (enable(0), reg_in(2), n15);
  U18: mu111 PORT MAP (n14, n15, enable(1), n13);
  U23: mu111 PORT MAP (n18, n19, enable(0), n17);
  U27: mu111 PORT MAP (n22, n23, enable(0), n21);
  U25: na210 PORT MAP (reg_in(1), enable(1), n18);
  U30: na210 PORT MAP (reg_in(0), enable(1), n22);
  U28: na210 PORT MAP (enc_in(0), n20, n23);
  U24: na210 PORT MAP (enc_in(1), n20, n19);

END extracted;



