-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 15-Dec-2016 9:30:30
-- Path: /home/jtams/Documents/new_pos/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Adder_5bits IS

  SIGNAL n50: STD_LOGIC;
  SIGNAL n32: STD_LOGIC;
  SIGNAL n31: STD_LOGIC;
  SIGNAL n33: STD_LOGIC;
  SIGNAL n46: STD_LOGIC;
  SIGNAL n48: STD_LOGIC;
  SIGNAL n47: STD_LOGIC;
  SIGNAL n49: STD_LOGIC;
  SIGNAL n34: STD_LOGIC;
  SIGNAL n40: STD_LOGIC;
  SIGNAL n44: STD_LOGIC;
  SIGNAL n45: STD_LOGIC;
  SIGNAL n43: STD_LOGIC;
  SIGNAL n36: STD_LOGIC;
  SIGNAL n42: STD_LOGIC;
  SIGNAL n38: STD_LOGIC;
  SIGNAL n39: STD_LOGIC;
  SIGNAL n41: STD_LOGIC;
  SIGNAL n35: STD_LOGIC;
  SIGNAL n37: STD_LOGIC;

  SIGNAL new_pos_int: STD_LOGIC_VECTOR(3 DOWNTO 0);

BEGIN

  new_pos <= new_pos_int;


  U38: no210 PORT MAP (n38, n39, n37);
  U37: no210 PORT MAP (n36, n37, n35);
  U45: no210 PORT MAP (n44, n45, n42);
  U48: no210 PORT MAP (new_pos_int(0), n49, n44);
  U47: no210 PORT MAP (n47, n48, n46);
  U46: no210 PORT MAP (n46, input_direction10(1), n45);
  U39: no210 PORT MAP (n40, n34, n36);
  U42: iv110 PORT MAP (n42, n39);
  U55: iv110 PORT MAP (n48, new_pos_int(0));
  U49: iv110 PORT MAP (n47, n49);
  U54: iv110 PORT MAP (input_direction10(1), n34);
  U40: iv110 PORT MAP (n41, n40);
  U41: na210 PORT MAP (n39, n38, n41);
  U44: ex210 PORT MAP (input_direction10(1), n42, n43);
  U43: ex210 PORT MAP (n38, n43, new_pos_int(2));
  U36: ex210 PORT MAP (n34, n35, n33);
  U34: ex210 PORT MAP (n33, old_pos(3), n32);
  U35: ex210 PORT MAP (n33, old_pos(7), n31);
  U53: ex210 PORT MAP (n34, n48, n50);
  U51: ex210 PORT MAP (n50, n47, new_pos_int(1));
  U50: mu111 PORT MAP (old_pos(6), old_pos(2), input_direction10(0), n38);
  U56: mu111 PORT MAP (old_pos(4), old_pos(0), input_direction10(0), n48);
  U52: mu111 PORT MAP (old_pos(5), old_pos(1), input_direction10(0), n47);
  U33: mu111 PORT MAP (n31, n32, input_direction10(0), new_pos_int(3));

END extracted;



