-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 17-Dec-2016 20:43:55
-- Path: /home/aptschipper/EPO16_12/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pg_fsm IS

  SIGNAL n23: STD_LOGIC;
  SIGNAL state: STD_LOGIC;
  SIGNAL n26: STD_LOGIC;
  SIGNAL n24: STD_LOGIC;
  SIGNAL n25: STD_LOGIC;

  SIGNAL tank_y_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_x_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_or_out_int: STD_LOGIC_VECTOR(1 DOWNTO 0);

BEGIN

  tank_y_out <= tank_y_out_int;
  tank_x_out <= tank_x_out_int;
  tank_or_out <= tank_or_out_int;


  U38: mu111 PORT MAP (tank_y_reg(2), tank_y_in(2), state, tank_y_out_int(2));
  U37: mu111 PORT MAP (tank_y_reg(3), tank_y_in(3), state, tank_y_out_int(3));
  U43: mu111 PORT MAP (tank_x_reg(1), tank_x_in(1), state, tank_x_out_int(1));
  U40: mu111 PORT MAP (tank_y_reg(0), tank_y_in(0), state, tank_y_out_int(0));
  U39: mu111 PORT MAP (tank_y_reg(1), tank_y_in(1), state, tank_y_out_int(1));
  U46: mu111 PORT MAP (tank_or_reg(0), tank_or_in(0), n25, tank_or_out_int(0));
  U41: mu111 PORT MAP (tank_x_reg(3), tank_x_in(3), state, tank_x_out_int(3));
  U42: mu111 PORT MAP (tank_x_reg(2), tank_x_in(2), state, tank_x_out_int(2));
  U45: mu111 PORT MAP (tank_or_reg(1), tank_or_in(1), n25, tank_or_out_int(1));
  U44: mu111 PORT MAP (tank_x_reg(0), tank_x_in(0), n25, tank_x_out_int(0));
  state_reg: dfr11 PORT MAP (n23, reset, clk, state);
  U36: iv110 PORT MAP (n24, n25);
  U35: iv110 PORT MAP (state, n24);
  U48: na210 PORT MAP (update_pos(2), update_pos(0), n26);
  U47: no310 PORT MAP (n26, update_pos(1), n25, n23);

END extracted;



