-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 17-Dec-2016 20:45:45
-- Path: /home/aptschipper/EPO16_12/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pg_hrg IS


  SIGNAL hit_out_int: STD_LOGIC;

BEGIN

  hit_out <= hit_out_int;


  hit_reg_reg: dfr11 PORT MAP (hit_in, reset, clk, hit_out_int);

END extracted;



