-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 17-Dec-2016 20:55:46
-- Path: /home/aptschipper/EPO16_12/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pg_pxc IS

  SIGNAL n25: STD_LOGIC;
  SIGNAL n26: STD_LOGIC;
  SIGNAL n24: STD_LOGIC;
  SIGNAL n19: STD_LOGIC;
  SIGNAL n15: STD_LOGIC;
  SIGNAL n20: STD_LOGIC;
  SIGNAL n16: STD_LOGIC;
  SIGNAL n18: STD_LOGIC;
  SIGNAL n17: STD_LOGIC;
  SIGNAL n22: STD_LOGIC;
  SIGNAL n21: STD_LOGIC;
  SIGNAL n23: STD_LOGIC;
  SIGNAL n28: STD_LOGIC;
  SIGNAL n27: STD_LOGIC;

  SIGNAL intersect_int: STD_LOGIC;

BEGIN

  intersect <= intersect_int;


  U25: no210 PORT MAP (n25, n26, n24);
  U16: no210 PORT MAP (n15, n16, intersect_int);
  U18: no210 PORT MAP (n19, n20, n18);
  U21: no210 PORT MAP (n21, n22, n17);
  U28: no210 PORT MAP (n27, n28, n23);
  U26: ex210 PORT MAP (x_video(1), x_tank(1), n26);
  U27: ex210 PORT MAP (x_video(0), x_tank(0), n25);
  U20: ex210 PORT MAP (y_video(0), y_tank(0), n19);
  U19: ex210 PORT MAP (y_video(1), y_tank(1), n20);
  U23: ex210 PORT MAP (y_video(2), y_tank(2), n21);
  U22: ex210 PORT MAP (y_video(3), y_tank(3), n22);
  U30: ex210 PORT MAP (x_video(2), x_tank(2), n27);
  U29: ex210 PORT MAP (x_video(3), x_tank(3), n28);
  U17: na210 PORT MAP (n17, n18, n16);
  U24: na210 PORT MAP (n23, n24, n15);

END extracted;



