-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 17-Dec-2016 20:50:24
-- Path: /home/aptschipper/EPO16_12/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pg_prg IS

  SIGNAL n1: STD_LOGIC;
  SIGNAL n2: STD_LOGIC;
  SIGNAL n5: STD_LOGIC;
  SIGNAL n6: STD_LOGIC;
  SIGNAL n3: STD_LOGIC;
  SIGNAL n4: STD_LOGIC;

  SIGNAL tank_x_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_y_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_or_out_int: STD_LOGIC_VECTOR(1 DOWNTO 0);

BEGIN

  tank_x_out <= tank_x_out_int;
  tank_y_out <= tank_y_out_int;
  tank_or_out <= tank_or_out_int;


  or_in_reg_reg_0_inst: dfr11 PORT MAP (tank_or_in(0), reset, clk, tank_or_out_int(0));
  x_in_reg_reg_2_inst: dfr11 PORT MAP (tank_x_in(2), reset, clk, tank_x_out_int(2));
  x_in_reg_reg_3_inst: dfr11 PORT MAP (tank_x_in(3), reset, clk, tank_x_out_int(3));
  y_in_reg_reg_2_inst: dfr11 PORT MAP (tank_y_in(2), reset, clk, tank_y_out_int(2));
  x_in_reg_reg_1_inst: dfr11 PORT MAP (tank_x_in(1), reset, clk, tank_x_out_int(1));
  y_in_reg_reg_3_inst: dfr11 PORT MAP (tank_y_in(3), reset, clk, tank_y_out_int(3));
  y_in_reg_reg_1_inst: dfr11 PORT MAP (tank_y_in(1), reset, clk, tank_y_out_int(1));
  U3: iv110 PORT MAP (n1, n2);
  U7: iv110 PORT MAP (n5, n6);
  U5: iv110 PORT MAP (n3, n4);
  U4: no210 PORT MAP (reset, tank_y_in(0), n1);
  U8: no210 PORT MAP (reset, tank_or_in(1), n5);
  U6: no210 PORT MAP (reset, tank_x_in(0), n3);
  y_in_reg_reg_0_inst: dfn10 PORT MAP (n2, clk, tank_y_out_int(0));
  or_in_reg_reg_1_inst: dfn10 PORT MAP (n6, clk, tank_or_out_int(1));
  x_in_reg_reg_0_inst: dfn10 PORT MAP (n4, clk, tank_x_out_int(0));

END extracted;



