-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 17-Dec-2016 21:05:17
-- Path: /home/aptschipper/EPO16_12/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Pg_tkc IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42, N_43, N_44, N_45, N_46, N_47, N_48: STD_LOGIC;
  SIGNAL N_49, N_50, N_51, N_52, N_53, N_54, N_55, N_56: STD_LOGIC;
  SIGNAL N_57, N_58, N_59, N_60, N_61, N_62, N_63, N_64: STD_LOGIC;
  SIGNAL N_65, N_66, N_67, N_68, N_69, N_70, N_71, N_72: STD_LOGIC;
  SIGNAL N_73, N_74, N_75, N_76, N_77, N_78, N_79, N_80: STD_LOGIC;
  SIGNAL N_81, N_82, N_83, N_84: STD_LOGIC;
  SIGNAL n4: STD_LOGIC;
  SIGNAL n3: STD_LOGIC;
  SIGNAL intersections_0_port: STD_LOGIC;
  SIGNAL intersections_2_port: STD_LOGIC;
  SIGNAL intersections_1_port: STD_LOGIC;
  SIGNAL intersections_5_port: STD_LOGIC;
  SIGNAL intersections_4_port: STD_LOGIC;
  SIGNAL intersections_3_port: STD_LOGIC;

  SIGNAL intersect_int: STD_LOGIC;

BEGIN

  intersect <= intersect_int;


  U4: na210 PORT MAP (n3, n4, intersect_int);
  l5_U17: na210 PORT MAP (N_46, N_44, N_41);
  l1_U17: na210 PORT MAP (N_45, N_43, N_40);
  l2_U17: na210 PORT MAP (N_18, N_16, N_14);
  l0_U17: na210 PORT MAP (N_17, N_15, N_12);
  l3_U17: na210 PORT MAP (N_79, N_78, N_76);
  l4_U17: na210 PORT MAP (N_65, N_64, N_63);
  l5_U24: na210 PORT MAP (N_52, N_34, N_37);
  l1_U24: na210 PORT MAP (N_51, N_33, N_36);
  l2_U24: na210 PORT MAP (N_24, N_6, N_10);
  l0_U24: na210 PORT MAP (N_23, N_5, N_8);
  l3_U24: na210 PORT MAP (N_82, N_73, N_74);
  l4_U24: na210 PORT MAP (N_70, N_59, N_61);
  U6: no310 PORT MAP (intersections_0_port, intersections_2_port, intersections_1_port, n3);
  U5: no310 PORT MAP (intersections_3_port, intersections_5_port, intersections_4_port, n4);
  l5_U25: no210 PORT MAP (N_32, N_31, N_34);
  l1_U25: no210 PORT MAP (N_29, N_30, N_33);
  l2_U25: no210 PORT MAP (N_3, N_4, N_6);
  l0_U25: no210 PORT MAP (N_1, N_2, N_5);
  l3_U25: no210 PORT MAP (N_69, N_68, N_73);
  l4_U25: no210 PORT MAP (N_57, N_58, N_59);
  l5_U16: no210 PORT MAP (N_37, N_41, intersections_5_port);
  l1_U16: no210 PORT MAP (N_36, N_40, intersections_1_port);
  l2_U16: no210 PORT MAP (N_10, N_14, intersections_2_port);
  l0_U16: no210 PORT MAP (N_8, N_12, intersections_0_port);
  l3_U16: no210 PORT MAP (N_74, N_76, intersections_3_port);
  l4_U16: no210 PORT MAP (N_61, N_63, intersections_4_port);
  l5_U18: no210 PORT MAP (N_38, N_42, N_44);
  l1_U18: no210 PORT MAP (N_35, N_39, N_43);
  l2_U18: no210 PORT MAP (N_9, N_13, N_16);
  l0_U18: no210 PORT MAP (N_7, N_11, N_15);
  l3_U18: no210 PORT MAP (N_75, N_77, N_78);
  l4_U18: no210 PORT MAP (N_60, N_62, N_64);
  l5_U21: no210 PORT MAP (N_49, N_50, N_46);
  l1_U21: no210 PORT MAP (N_48, N_47, N_45);
  l2_U21: no210 PORT MAP (N_22, N_21, N_18);
  l0_U21: no210 PORT MAP (N_20, N_19, N_17);
  l3_U21: no210 PORT MAP (N_80, N_81, N_79);
  l4_U21: no210 PORT MAP (N_67, N_66, N_65);
  l5_U28: no210 PORT MAP (N_55, N_56, N_52);
  l1_U28: no210 PORT MAP (N_54, N_53, N_51);
  l2_U28: no210 PORT MAP (N_28, N_27, N_24);
  l0_U28: no210 PORT MAP (N_26, N_25, N_23);
  l3_U28: no210 PORT MAP (N_83, N_84, N_82);
  l4_U28: no210 PORT MAP (N_72, N_71, N_70);
  l5_U26: ex210 PORT MAP (x_video(1), x_tank5(1), N_31);
  l1_U26: ex210 PORT MAP (x_video(1), x_tank1(1), N_30);
  l2_U26: ex210 PORT MAP (x_video(1), x_tank2(1), N_4);
  l0_U26: ex210 PORT MAP (x_video(1), x_tank0(1), N_2);
  l3_U26: ex210 PORT MAP (x_video(1), x_tank3(1), N_68);
  l4_U26: ex210 PORT MAP (x_video(1), x_tank4(1), N_58);
  l5_U27: ex210 PORT MAP (x_video(0), x_tank5(0), N_32);
  l1_U27: ex210 PORT MAP (x_video(0), x_tank1(0), N_29);
  l2_U27: ex210 PORT MAP (x_video(0), x_tank2(0), N_3);
  l0_U27: ex210 PORT MAP (x_video(0), x_tank0(0), N_1);
  l3_U27: ex210 PORT MAP (x_video(0), x_tank3(0), N_69);
  l4_U27: ex210 PORT MAP (x_video(0), x_tank4(0), N_57);
  l5_U20: ex210 PORT MAP (y_video(0), y_tank5(0), N_38);
  l1_U20: ex210 PORT MAP (y_video(0), y_tank1(0), N_35);
  l2_U20: ex210 PORT MAP (y_video(0), y_tank2(0), N_9);
  l0_U20: ex210 PORT MAP (y_video(0), y_tank0(0), N_7);
  l3_U20: ex210 PORT MAP (y_video(0), y_tank3(0), N_75);
  l4_U20: ex210 PORT MAP (y_video(0), y_tank4(0), N_60);
  l5_U19: ex210 PORT MAP (y_video(1), y_tank5(1), N_42);
  l1_U19: ex210 PORT MAP (y_video(1), y_tank1(1), N_39);
  l2_U19: ex210 PORT MAP (y_video(1), y_tank2(1), N_13);
  l0_U19: ex210 PORT MAP (y_video(1), y_tank0(1), N_11);
  l3_U19: ex210 PORT MAP (y_video(1), y_tank3(1), N_77);
  l4_U19: ex210 PORT MAP (y_video(1), y_tank4(1), N_62);
  l5_U23: ex210 PORT MAP (y_video(2), y_tank5(2), N_49);
  l1_U23: ex210 PORT MAP (y_video(2), y_tank1(2), N_48);
  l2_U23: ex210 PORT MAP (y_video(2), y_tank2(2), N_22);
  l0_U23: ex210 PORT MAP (y_video(2), y_tank0(2), N_20);
  l3_U23: ex210 PORT MAP (y_video(2), y_tank3(2), N_80);
  l4_U23: ex210 PORT MAP (y_video(2), y_tank4(2), N_67);
  l5_U22: ex210 PORT MAP (y_video(3), y_tank5(3), N_50);
  l1_U22: ex210 PORT MAP (y_video(3), y_tank1(3), N_47);
  l2_U22: ex210 PORT MAP (y_video(3), y_tank2(3), N_21);
  l0_U22: ex210 PORT MAP (y_video(3), y_tank0(3), N_19);
  l3_U22: ex210 PORT MAP (y_video(3), y_tank3(3), N_81);
  l4_U22: ex210 PORT MAP (y_video(3), y_tank4(3), N_66);
  l5_U30: ex210 PORT MAP (x_video(2), x_tank5(2), N_55);
  l1_U30: ex210 PORT MAP (x_video(2), x_tank1(2), N_54);
  l2_U30: ex210 PORT MAP (x_video(2), x_tank2(2), N_28);
  l0_U30: ex210 PORT MAP (x_video(2), x_tank0(2), N_26);
  l3_U30: ex210 PORT MAP (x_video(2), x_tank3(2), N_83);
  l4_U30: ex210 PORT MAP (x_video(2), x_tank4(2), N_72);
  l5_U29: ex210 PORT MAP (x_video(3), x_tank5(3), N_56);
  l1_U29: ex210 PORT MAP (x_video(3), x_tank1(3), N_53);
  l2_U29: ex210 PORT MAP (x_video(3), x_tank2(3), N_27);
  l0_U29: ex210 PORT MAP (x_video(3), x_tank0(3), N_25);
  l3_U29: ex210 PORT MAP (x_video(3), x_tank3(3), N_84);
  l4_U29: ex210 PORT MAP (x_video(3), x_tank4(3), N_71);

END extracted;



