-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 27-Nov-2016 21:36:33
-- Path: /home/ndekoeijer/Documents/Tanks-EPO3/pixelgenerator/memory/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Tank_pos_reg IS


  SIGNAL tank_x_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_y_out_int: STD_LOGIC_VECTOR(3 DOWNTO 0);
  SIGNAL tank_or_out_int: STD_LOGIC_VECTOR(1 DOWNTO 0);

BEGIN

  tank_x_out <= tank_x_out_int;
  tank_y_out <= tank_y_out_int;
  tank_or_out <= tank_or_out_int;


  or_in_reg_reg_1_inst: dfr11 PORT MAP (tank_or_in(1), reset, update_pos, tank_or_out_int(1));
  y_in_reg_reg_0_inst: dfr11 PORT MAP (tank_y_in(0), reset, update_pos, tank_y_out_int(0));
  x_in_reg_reg_3_inst: dfr11 PORT MAP (tank_x_in(3), reset, update_pos, tank_x_out_int(3));
  y_in_reg_reg_2_inst: dfr11 PORT MAP (tank_y_in(2), reset, update_pos, tank_y_out_int(2));
  or_in_reg_reg_0_inst: dfr11 PORT MAP (tank_or_in(0), reset, update_pos, tank_or_out_int(0));
  x_in_reg_reg_1_inst: dfr11 PORT MAP (tank_x_in(1), reset, update_pos, tank_x_out_int(1));
  x_in_reg_reg_0_inst: dfr11 PORT MAP (tank_x_in(0), reset, update_pos, tank_x_out_int(0));
  y_in_reg_reg_3_inst: dfr11 PORT MAP (tank_y_in(3), reset, update_pos, tank_y_out_int(3));
  y_in_reg_reg_1_inst: dfr11 PORT MAP (tank_y_in(1), reset, update_pos, tank_y_out_int(1));
  x_in_reg_reg_2_inst: dfr11 PORT MAP (tank_x_in(2), reset, update_pos, tank_x_out_int(2));

END extracted;



