-- Generated by: xvhdl 3.02 5-Mar-2013
-- Date: 27-Nov-2016 20:42:46
-- Path: /home/ndekoeijer/Documents/Tanks-EPO3/pixelgenerator/memory/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Tank_hit_reg IS


  SIGNAL hit_out_int: STD_LOGIC;

BEGIN

  hit_out <= hit_out_int;


  hit_reg_reg: dfr11 PORT MAP (hit_in, reset, clk, hit_out_int);

END extracted;



